---
exclude: ^(\.[^/]*cache(__)?/.*|(.*/)?\.coverage)$
repos:
  # Perform Markdown formatting before other hooks "fixing" line endings:
  # PROBLEM: it alters the .md file permissions from 644 to 600 :(
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.17
    hooks:
      - id: mdformat
        name: Format Markdown
        entry: mdformat  # Executable to run, with fixed options
        language: python
        types: [markdown]
        args: [--wrap, '75', --number]
        additional_dependencies:
          - mdformat-toc
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.4
    hooks:
      - id: forbid-crlf
      - id: remove-crlf
      - id: forbid-tabs
        exclude: tests/resources/main.*_with_license.cpp
      - id: remove-tabs
        exclude: tests/resources/main.*_with_license.cpp
      - id: chmod
        args: ['644']
        exclude: (\.md$|^tests/resources/.*shebang)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        files: ''
        exclude: tests/resources/main.*_with_license.cpp
      - id: check-yaml
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
      - id: pyupgrade
        args:
          - --py37-plus
        exclude: ^tests/resources/.*
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        exclude: ^tests/resources/
  - repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
    rev: v1.0.6
    hooks:
      - id: python-bandit-vulnerability-check
        args: [--skip, 'B101', --recursive, .]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        args:
          - --ignore-missing-imports
          - --install-types
          - --non-interactive
          - --check-untyped-defs
          - --show-error-codes
          - --show-error-context
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        # 3x faster than the official pylint hook, and has no issue with imports
        # (tested with: time pre-commit run pylint --all-files)
        language: system
        entry: pylint
        files: \.py$
        exclude: ^tests/resources/.*(init_with_license|todo)
      - id: pytest
        name: pytest
        language: python
        additional_dependencies: [pytest, pytest-cov, coverage, rapidfuzz]
        entry: pytest -vv
        require_serial: true
        pass_filenames: false
        files: \.py$
