repos:
-   repo: git://github.com/potiuk/pre-commit-hooks
    sha: v1.1.7
    hooks:
    -   id: forbid-crlf
    -   id: remove-crlf
    -   id: forbid-tabs
    -   id: remove-tabs
-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v2.2.1
    hooks:
    -   id: trailing-whitespace
        files: ''
        args:
        - --no-markdown-linebreak-ext
    -   id: check-json
    -   id: check-yaml
-   repo: git://github.com/pre-commit/mirrors-pylint
    sha: v2.3.1
    hooks:
    -   id: pylint
        args:
        - --rcfile=.pylintrc
        - --reports=no
        exclude: ^tests/resources/.*_todo.*$
-   repo: local
    hooks:
    -   id: py.test
        name: py.test
        language: system
        entry: sh -c 'pip install -e .[testing] && python -m pytest'
        files: ''
