---
exclude: ^(\.[^/]*cache(__)?/.*|\.coverage)$
repos:
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.13
    hooks:
      - id: forbid-crlf
      - id: remove-crlf
      - id: forbid-tabs
        exclude: tests/resources/main.*_with_license.cpp
      - id: remove-tabs
        exclude: tests/resources/main.*_with_license.cpp
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: trailing-whitespace
        files: ''
        exclude: tests/resources/main.*_with_license.cpp
      - id: check-yaml
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: v3.0.0a4
    hooks:
      - id: pylint
        args:
          - --rcfile=.pylintrc
          - --reports=no
        exclude: ^tests/resources/.*(init_with_license\.py|todo).*$
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        stages: [manual]   # Skip in automated run for now
        args:
          - --safe
          - --quiet
        exclude: ^tests/resources/.*(init_with_license\.py|todo).*$
  - repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
    rev: v1.0.6
    hooks:
      - id: python-bandit-vulnerability-check
        args: [--skip, 'B101', --recursive, .]   # Example for skipping rule
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.942
    hooks:
      - id: mypy
        args:
          - --ignore-missing-imports
          - --install-types
          - --non-interactive
          - --check-untyped-defs
          - --show-error-codes
          - --show-error-context
  - repo: local
    hooks:
      - id: py.test
        name: py.test
        language: python
        additional_dependencies: [pytest, pytest-cov, coverage, fuzzywuzzy, python-Levenshtein-wheels]
        entry: pytest -sv
        require_serial: true
        pass_filenames: false
        files: \.py$
